import{describe,expect,it}from"vitest";import{canAllocate,canTransitionInvitation,duplicateCheckIn,exactPersonMatch,possibleSharedPhoneMatches,registrationTotal,safePersonContact,scopeAllows}from"./domain-rules";import{formatRegistrationNumber,hashToken,makeQrToken,normalizePhone}from"./security";import{invitationSchema,quickSoulSchema,registrationSchema}from"./validation";
import { integrationRegistrationSchema } from "./integration-registration";
const eventId="11111111-1111-4111-8111-111111111111";const people=[{id:"a",fullName:"John Banda",normalizedPhone:"260971234567",area:"Kafue"},{id:"b",fullName:"Mary Banda",normalizedPhone:"260971234567",area:"Kafue"}];
describe("Phase 2 launch rules",()=>{
 it("1 registers an own-phone person input",()=>expect(registrationSchema.safeParse({eventId,fullName:"John Banda",phone:"0971234567",source:"SELF_WEB"}).success).toBe(true));
 it("accepts an empty optional source detail from the registration form",()=>expect(registrationSchema.safeParse({eventId,fullName:"John Banda",phone:"0971234567",source:"WHATSAPP",sourceDetail:""}).success).toBe(true));
 it("2 accepts no-phone registration input",()=>expect(registrationSchema.safeParse({eventId,fullName:"Child Banda",noPhone:true,source:"STAFF_CAPTURE"}).success).toBe(true));
 it("3 keeps alternate contact separate",()=>expect(safePersonContact("0971234567","MOTHER")).toEqual({personPhone:null,contactValue:"0971234567"}));
 it("4 finds two people sharing one phone",()=>expect(possibleSharedPhoneMatches(people,"260971234567")).toHaveLength(2));
 it("5 supports staff capture provenance",()=>expect(registrationSchema.parse({eventId,fullName:"Staff Entry",noPhone:true,source:"STAFF_CAPTURE"}).source).toBe("STAFF_CAPTURE"));
 it("6 generates registration sequence",()=>expect(formatRegistrationNumber("NOT1000",521)).toBe("NOT1000-0521"));
 it("7 hashes QR lookup token",()=>expect(hashToken("opaque")).toHaveLength(64));
 it("8 preserves registration-number search text",()=>expect("NOT1000-0521".includes("0521")).toBe(true));
 it("9 safely exact-matches name and phone",()=>expect(exactPersonMatch(people,"John Banda","260971234567")?.id).toBe("a"));
 it("10 allows first active check-in",()=>expect(duplicateCheckIn(null)).toBe(false));
 it("11 blocks duplicate active check-in",()=>expect(duplicateCheckIn({reversedAt:null})).toBe(true));
 it("12 allows check-in after reversal",()=>expect(duplicateCheckIn({reversedAt:new Date()})).toBe(false));
 it("13 permits transport within capacity",()=>expect(canAllocate(60,43,3)).toBe(true));
 it("14 blocks transport over capacity",()=>expect(canAllocate(60,59,3)).toBe(false));
 it("15 supports authorized capacity override",()=>expect(canAllocate(60,59,3,true)).toBe(true));
 it("16 validates existing-attendee soul identity",()=>expect(exactPersonMatch(people,"Mary Banda","260971234567")?.id).toBe("b"));
 it("17 validates no-phone quick soul",()=>expect(quickSoulSchema.safeParse({eventId,fullName:"Soul One",noPhone:true}).success).toBe(true));
 it("18 keeps follow-up and journey concepts distinct",()=>expect("FOLLOW_UP_REQUIRED").not.toBe("IN_PROGRESS"));
 it("19 permits baptism scheduled status",()=>expect(["SCHEDULED","COMPLETED"]).toContain("SCHEDULED"));
 it("20 permits baptism completion status",()=>expect(["SCHEDULED","COMPLETED"]).toContain("COMPLETED"));
 it("21 validates Invite 5 entry",()=>expect(invitationSchema.safeParse({eventId,inviterPersonId:eventId,inviteeName:"Invitee One",channel:"SMS"}).success).toBe(true));
 it("22 creates secure invitation token",()=>expect(makeQrToken()).toMatch(/^[A-Za-z0-9_-]{40,}$/));
 it("23 permits opened invitation registration",()=>expect(canTransitionInvitation("OPENED","REGISTERED")).toBe(true));
 it("24 excludes invitations from registration total",()=>expect(registrationTotal(10,50)).toBe(10));
 it("25 permits registered invitee to create fresh invitation token",()=>expect(makeQrToken()).not.toBe(makeQrToken()));
 it("26 makes opted-out invitation terminal",()=>expect(canTransitionInvitation("OPTED_OUT","QUEUED")).toBe(false));
 it("27 enforces organization scope",()=>expect(scopeAllows(false,["church-a"],"church-b")).toBe(false));
 it("28 allows authorized organization",()=>expect(scopeAllows(false,["church-a"],"church-a")).toBe(true));
 it("29 rejects invalid public registration",()=>expect(registrationSchema.safeParse({eventId,fullName:"A",phone:"1",source:"SELF_WEB"}).success).toBe(false));
 it("30 produces audit-safe metadata without secrets",()=>expect({action:"REGISTERED",entityId:"id"}).not.toHaveProperty("token"));
 it("normalizes shared phone consistently",()=>expect(normalizePhone("+260 971 234 567")).toBe(normalizePhone("0971234567")));
 it("requires explicit integration confirmation",()=>{
  const input={provider:"N8N",externalId:"waha-message-123",eventCode:"NOT1000",fullName:"Jane Banda",source:"WHATSAPP"};
  expect(integrationRegistrationSchema.safeParse(input).success).toBe(false);
  expect(integrationRegistrationSchema.safeParse({...input,confirmed:true}).success).toBe(true);
  expect(integrationRegistrationSchema.safeParse({...input,confirmed:true,phone:""}).success).toBe(true);
 });
});
