import{NextRequest,NextResponse}from"next/server";import{getSession}from"@/lib/auth";import{db}from"@/lib/db";import{organizationScope}from"@/lib/scope";
const csvCell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;
export async function GET(req:NextRequest){const session=await getSession();if(!session?.permissions.includes("reports.export"))return NextResponse.json({error:"Unauthorized"},{status:401});const eventId=req.nextUrl.searchParams.get("eventId")||"";const type=req.nextUrl.searchParams.get("type")||"registrations";const event=await db.event.findUnique({where:{id:eventId}});if(!event)return NextResponse.json({error:"Event not found"},{status:404});const scope=await organizationScope("reports.export");if(!scope.unrestricted&&(!event.organizationId||!scope.organizationIds.includes(event.organizationId)))return NextResponse.json({error:"Forbidden"},{status:403});let headers:string[]=[];let rows:unknown[][]=[];
if(type==="registrations"){const data=await db.eventRegistration.findMany({where:{eventId,deletedAt:null},include:{person:true}});headers=["Registration","Name","Phone","Area","Source","Party size","First timer"];rows=data.map(x=>[x.registrationNumber,x.person.fullName,x.person.phone,x.person.area,x.source,x.partySize,x.firstTimer])}
else if(type==="attendance"){const data=await db.attendance.findMany({where:{eventId,reversedAt:null},include:{registration:{include:{person:true}}}});headers=["Registration","Name","Checked in","Method"];rows=data.map(x=>[x.registration.registrationNumber,x.registration.person.fullName,x.checkedInAt.toISOString(),x.method])}
else if(type==="transport"){const data=await db.transportAssignment.findMany({where:{registration:{eventId}},include:{registration:{include:{person:true}},route:true,vehicle:true,pickupPoint:true}});headers=["Registration","Name","Route","Vehicle","Pickup","Seats"];rows=data.map(x=>[x.registration.registrationNumber,x.registration.person.fullName,x.route?.code,x.vehicle?.code,x.pickupPoint?.name,x.seatsRequired])}
else if(type==="souls"){const data=await db.salvationDecision.findMany({where:{eventId},include:{person:true}});headers=["Name","Phone","Area","Decision time"];rows=data.map(x=>[x.person.fullName,x.person.phone,x.person.area,x.decidedAt.toISOString()])}
else if(type==="invitations"){const data=await db.eventInvitation.findMany({where:{eventId},include:{inviter:true}});headers=["Invitee","Phone","Inviter","Channel","Status","Created"];rows=data.map(x=>[x.inviteeName,x.inviteePhone,x.inviter.fullName,x.channel,x.status,x.createdAt.toISOString()])}
else if(type==="follow-up"){const data=await db.followUpAssignment.findMany({where:{eventId},include:{person:true,assignedWorker:true}});headers=["Name","Phone","Worker","Status","Next follow-up"];rows=data.map(x=>[x.person.fullName,x.person.phone,x.assignedWorker?.name,x.status,x.nextFollowUpAt?.toISOString()])}
else return NextResponse.json({error:"Unknown report"},{status:400});const body=[headers,...rows].map(row=>row.map(csvCell).join(",")).join("\r\n");return new NextResponse(body,{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":`attachment; filename="${event.code}-${type}.csv"`}})}
