"use client";
import { useActionState, useEffect, useState } from "react";
import Image from "next/image";
import QRCode from "qrcode";
import { CalendarCheck, CheckCircle2 } from "lucide-react";
import { registerAction } from "@/app/actions";
import { InviteFiveForm } from "@/components/invite-five-form";

export function RegistrationForm({event,invitation}:{event:{id:string;name:string;dateLabel:string;transportEnabled:boolean};invitation?:{token:string;name:string;phone:string}}){
 const[state,action,pending]=useActionState(registerAction,{ok:false});const[qr,setQr]=useState("");
 useEffect(()=>{if(state.qrToken)QRCode.toDataURL(state.qrToken,{width:320,margin:1,color:{dark:"#0c4e30",light:"#ffffff"}}).then(setQr)},[state.qrToken]);
 if(state.ok)return <div className="confirmation"><CheckCircle2 size={48} color="#146c43"/><p className="eyebrow">Registration confirmed</p><h2>{state.registrationNumber}</h2><p><CalendarCheck size={18} style={{verticalAlign:"middle"}}/> {event.dateLabel}</p>{qr&&<Image className="qr" src={qr} width={320} height={320} unoptimized alt={`QR code for ${state.registrationNumber}`}/>}<div className="notice">Keep this registration number and QR code for transport and event check-in.</div>{state.personId&&state.qrToken&&<InviteFiveForm eventId={event.id} personId={state.personId} registrationQrToken={state.qrToken}/>}</div>;
 const sources=["WHATSAPP","FACEBOOK","INSTAGRAM","TIKTOK","CHURCH","FRIEND","RADIO","SMS","OTHER"] as const;
 return <form action={action} className="form-grid registration-form"><input type="hidden" name="eventId" value={event.id}/>{invitation&&<input type="hidden" name="invitationToken" value={invitation.token}/>} {state.message&&<div className="notice error" role="alert">{state.message}</div>}<div className="field"><label htmlFor="fullName">Full name</label><input className="input" id="fullName" name="fullName" autoComplete="name" defaultValue={invitation?.name} required/></div><div className="field"><label htmlFor="phone">Mobile / contact number</label><input className="input" id="phone" name="phone" type="tel" inputMode="tel" placeholder="097 123 4567" defaultValue={invitation?.phone}/></div><label className="check"><input type="checkbox" name="noPhone"/><span>This person has no phone</span></label><div className="form-grid two"><div className="field"><label htmlFor="relationship">Whose number is this?</label><select className="select" id="relationship" name="relationship" defaultValue="SELF"><option value="SELF">Their own</option><option value="MOTHER">Mother</option><option value="FATHER">Father</option><option value="SPOUSE">Spouse</option><option value="GUARDIAN">Guardian</option><option value="FRIEND">Friend</option><option value="CHURCH_WORKER">Church worker</option><option value="OTHER">Other</option></select></div><div className="field"><label htmlFor="contactPerson">Contact person name</label><input className="input" id="contactPerson" name="contactPerson"/></div></div><div className="form-grid two"><div className="field"><label htmlFor="area">Area</label><input className="input" id="area" name="area" required/></div><div className="field"><label htmlFor="guestCount">Number of guests</label><input className="input" id="guestCount" name="guestCount" type="number" min="0" max="20" defaultValue="0"/></div></div><label className="check"><input type="checkbox" name="firstTimer"/><span>This is my first time attending</span></label>{event.transportEnabled&&<><label className="check"><input type="checkbox" name="transportRequired"/><span>I need transport</span></label><div className="field"><label htmlFor="pickupLocation">Preferred pickup area / location</label><input className="input" id="pickupLocation" name="pickupLocation"/></div></>}<div className="field"><label htmlFor="source">How did you hear about us?</label><select className="select" id="source" name="source" defaultValue="WHATSAPP">{sources.map(x=><option value={x} key={x}>{x[0]+x.slice(1).toLowerCase()}</option>)}</select></div><label className="check"><input type="checkbox" name="consentUpdates"/><span>I consent to receive event-related updates</span></label><button className="btn btn-accent registration-submit" disabled={pending}>{pending?"Registering...":"Complete registration"}</button></form>
}
